### ISSUE TITLE
UNet bug 

### ISSUE THREAD

**Issue by AlexeyKozhevin** [analysiscenter/dataset#132]
https://github.com/analysiscenter/dataset/blob/ae64502338ffe5b4475e2d94b2193364bb95a59b/dataset/models/tf/unet.py#L53

If 'body': dict(filters=[64, 128, 256, 512]), is not included to config, the following error raises
KeyError: 'Key body/filters not found'

**Comment by roman-kh** [comment]
Fixed in e33754c3cc5dd3c731120e38cc09aaafbcfc35fe
