### ISSUE TITLE
Image examples from dataset/examples/simple_but_ugly/ don't work out of the box

### ISSUE THREAD

**Issue by mikhailkin** [analysiscenter/dataset#224]
Hi!
I've tried to run several examples from the directory. For example, trying to run https://github.com/analysiscenter/dataset/tree/master/examples/simple_but_ugly fails with bunch of errors. Looks like there are no several files with definitions (random_scale, random_rotate, convert_to_pil, etc)

**Comment by roman-kh** [comment]
Unfortunately, simple_but_ugly examples are mainly outdated.
While we are working on new tutorials and examples, please, try opensets examples, for instance, https://github.com/analysiscenter/dataset/blob/master/examples/opensets/mnist_model3.py for a typical classfication task or mnist_model4.py for segmentation.

**Comment by mikhailkin** [comment]
Could you delete it?
Still the code doesn't work:

> dataset/dataset/variables.py in get(self, name, create, pipeline, *args, **kwargs)
>     145                 self.variable.create(name, *args, pipeline=pipeline, **kwargs)
>     146             else:
> --> 147                 raise KeyError("Variable '%s' does not exists" % name)
>     148         var = self.variables[name].get()
>     149         return var
> 
> KeyError: "Variable 'model' does not exists"

**Comment by mikhailkin** [comment]
Looks like error was in .print(V('current_loss'), model=**V**('model')) 
Should be .print(V('current_loss'), model=**C**('model'))
https://github.com/analysiscenter/dataset/blob/master/examples/opensets/mnist_model3.py#L44

**Comment by roman-kh** [comment]
You're absolutely right. Thank you so much.
Tomorrow we'll upload updated tutorials and remove outdated examples.

**Comment by mikhailkin** [comment]
Thank you.
The projects feels to be much better than similar, but a little bit unfinished. Looking forward to get demos, better overview with architecture principles would be valuable. I'm confused for your choice to use hierarchy instead of visitors for routine adaptation.
Also, I'm going to inject TensorBoard logs and planning to add sciopt usage.
Anyway the project is much closer for everyday usage than any I've seen before and far developed.

**Comment by roman-kh** [comment]
A first edition of updated tutorials are uploaded to https://github.com/analysiscenter/dataset/tree/master/examples/tutorial.
Please take a look when you have a spare time.
Look forward to your reply.

**Comment by roman-kh** [comment]
Closing. You might reopen it if needed.
