### ISSUE TITLE
Can't use list for preloaded data

### ISSUE THREAD

**Issue by mikhailkin** [analysiscenter/dataset#228]
Hi!
It looks like batches are generated like lists, so it is not worth to make extra conversions to numpy and vise-versa. 

Please, consider to fix https://github.com/analysiscenter/dataset/blob/master/dataset/batch.py#L372
I've fixed it with:
`            try:
                res = tuple(data_item[self.get_pos(data, comp, index)] if data_item is not None else None
                            for comp, data_item in zip(comps, _data))
            except TypeError:
                res = tuple(list(data_item[i] for i in self.get_pos(data, comp, index)) if data_item is not None else None
                            for comp, data_item in zip(comps, _data))
`
Quite ugly

Bellow you might find the example.
PS Let me know whether you prefer pull requests or issues. Thank you in advance.

`import sys
import numpy as np
sys.path.append("../..")
from dataset import Dataset, DatasetIndex, ImagesBatch

def show_images(batch):
    img = np.concatenate(batch.images, axis=1).reshape(-1, batch.images.shape[1] * len(batch))
    fig, ax = plt.subplots(1, figsize=(10, 4))
    ax.axis('off')
    ax.imshow(img, cmap="gray")
    plt.show()

S = 20
def gen_data(num_items, shape):
    index = np.arange(num_items)
//     data = np.random.randint(0, 255, size=num_items * shape[0] * shape[1])
//     data = data.reshape(num_items, shape[0], shape[1]).astype('uint8')
    data = list(np.random.randint(0, 255, size=shape[0] * shape[1]).reshape(shape[0], shape[1]) for i in range(num_items))
    ds = Dataset(index=index, batch_class=ImagesBatch, preloaded=data)
    return ds, data

// Create a dataset
print("Generating...")
dataset, images = gen_data(5, (S, S))

pipeline = (dataset.pipeline()
            .rotate(p=.5, angle=60, reshape=False)
           )
for b in pipeline.gen_batch(2, shuffle=False):
    show_images(b)`

**Comment by roman-kh** [comment]
You can just wrap list into `np.array`.
